/* Editorial content part 1: moods + genre guides. Part 2 (roadmap, hardware, faq) in js/data-content-2.js */
window.CONTENT = window.CONTENT || {};

window.CONTENT.moods = [
  { label: "🔥 Test my skill", desc: "Hardest, fairest, most rewarding. These respect you enough to let you fail.",
    games: ["sekiro","elden-ring","silksong","celeste","ultrakill","nine-sols","slay-the-spire","spelunky-2","noita","doom-eternal","battle-brothers","darktide"] },
  { label: "🧠 Big brain", desc: "Systems, logistics, deduction. For when you want to think, not react.",
    games: ["factorio","oxygen-not-included","into-the-breach","blue-prince","outer-wilds","return-of-the-obra-dinn","the-witness","balatro","old-world","dwarf-fortress","satisfactory","tactical-breach-wizards"] },
  { label: "🤝 Friends tonight", desc: "Drop-in fun with your PC friends. Roughly ordered from least to most coordination needed.",
    games: ["repo","lethal-company","helldivers-2","deep-rock-galactic","it-takes-two","split-fiction","valheim","monster-hunter-wilds","risk-of-rain-2","baldurs-gate-3","factorio","darktide"] },
  { label: "⏱️ 30 minutes", desc: "One run. One match. One level. Fits before bed.",
    games: ["balatro","hades-2","dead-cells","slay-the-spire","rocket-league","pizza-tower","into-the-breach","monster-train-2","enter-the-gungeon","roboquest","celeste","ultrakill"] },
  { label: "🗺️ Get lost", desc: "Worlds that reward wandering off the path.",
    games: ["elden-ring","outer-wilds","subnautica","hollow-knight","kenshi","prey-2017","stalker-2","kingdom-come-2","red-dead-2","blue-prince","caves-of-qud","valheim"] },
  { label: "📈 Number go up", desc: "Progression loops so good they should come with a warning.",
    games: ["path-of-exile-2","factorio","monster-hunter-world","nioh-2","against-the-storm","terraria","last-epoch","hades-2","stardew-valley","grim-dawn","mount-and-blade-2","v-rising"] },
  { label: "🎨 GPU showcase", desc: "Turn everything to max and watch your 9070 XT earn its keep.",
    games: ["cyberpunk-2077","alan-wake-2","red-dead-2","metro-exodus","stalker-2","assassins-creed-shadows","forza-horizon-5","talos-principle-2","doom-dark-ages","monster-hunter-wilds","expedition-33","kingdom-come-2"] },
  { label: "🎭 Story worth it", desc: "Story is your lowest priority — so these are only the ones so good it doesn't matter.",
    games: ["outer-wilds","expedition-33","baldurs-gate-3","nier-automata","witcher-3","alan-wake-2","red-dead-2","inscryption","portal-2","persona-5-royal","kingdom-come-2","cyberpunk-2077"] }
];

window.CONTENT.genreGuides = [
  { icon:"⚔️", name:"Soulslike & Action RPG", fit:"★★★★★ — your #1 genre on paper",
    body:"Deliberate combat, high stakes, exploration that rewards you with real power. This genre maxes gameplay, challenge and exploration simultaneously — three of your top priorities. Start with Elden Ring for open exploration or Sekiro for pure combat mastery, then work outward.",
    picks:["elden-ring","sekiro","lies-of-p","nioh-2","nine-sols"] },
  { icon:"🏭", name:"Automation & Colony Sims", fit:"★★★★★ — the non-action sweet spot",
    body:"If action games max gameplay/challenge, automation games max progression/creativity. Factorio is the purest; Satisfactory is prettier and more exploratory; Oxygen Not Included is the hardest. Fantastic in co-op — a shared factory is a shared project.",
    picks:["factorio","satisfactory","oxygen-not-included","rimworld","against-the-storm"] },
  { icon:"🎲", name:"Roguelikes & Deckbuilders", fit:"★★★★★ — bottomless replayability",
    body:"Short runs, permanent knowledge, escalating difficulty ladders. Roguelikes hit gameplay, challenge and progression in 30-minute doses. Hades II and Dead Cells for action; Slay the Spire and Balatro for decisions; Noita and Spelunky 2 for systems chaos.",
    picks:["hades-2","slay-the-spire","balatro","dead-cells","noita"] },
  { icon:"🔫", name:"Shooters", fit:"★★★★☆ — best in co-op and campaigns",
    body:"Single-player: DOOM Eternal and ULTRAKILL are combat puzzles at speed. Co-op: Helldivers 2, Deep Rock and Darktide are built for your friend group. Competitive: CS2 or Valorant for tactical, Apex or The Finals for movement. Immersive sims (Dishonored, Prey) add creativity on top.",
    picks:["doom-eternal","ultrakill","helldivers-2","deep-rock-galactic","dishonored-2"] },
  { icon:"🦋", name:"Metroidvania & Platformers", fit:"★★★★★ — Silksong alone justifies the genre",
    body:"Tight controls, interconnected maps, boss fights. Hollow Knight and Silksong are essential; Nine Sols is Sekiro in 2D; Celeste is the platforming skill test. Cheap, dense, and perfectly suited to a gameplay-first player.",
    picks:["silksong","hollow-knight","nine-sols","celeste","pizza-tower"] },
  { icon:"♟️", name:"Strategy & Tactics", fit:"★★★★☆ — deep, but lower on reflex gameplay",
    body:"Turn-based tactics (XCOM 2, Battle Brothers, Into the Breach) offer challenge and progression with zero twitch. 4X (Civ VI, Old World, Stellaris) is the ultimate progression loop. RTS (AoE4, SC2) is the ultimate challenge. Total War: Warhammer III does massive co-op campaigns.",
    picks:["xcom-2","battle-brothers","into-the-breach","age-of-empires-4","total-war-warhammer-3"] },
  { icon:"🤝", name:"Co-op Specialists", fit:"★★★★★ — your friends are on PC",
    body:"Games designed around a group. It Takes Two / Split Fiction for two players; Lethal Company / R.E.P.O. for chaos; Valheim / Enshrouded for long-term projects; Baldur's Gate 3 for a shared 100-hour campaign; Monster Hunter Wilds for endless hunts.",
    picks:["it-takes-two","repo","valheim","baldurs-gate-3","monster-hunter-wilds"] },
  { icon:"🏆", name:"Competitive", fit:"★★★★☆ — infinite challenge, needs commitment",
    body:"Pick one and go deep. Counter-Strike 2 (aim), Rocket League (mechanics), Street Fighter 6 / Tekken 8 (1v1 mastery), Dota 2 / Deadlock (depth). All run at extreme frame rates on your hardware. A 5-stack in CS2 or a Deadlock 6-stack is a lifelong hobby.",
    picks:["counter-strike-2","rocket-league","street-fighter-6","deadlock","apex-legends"] },
  { icon:"🧩", name:"Puzzle & Exploration", fit:"★★★★☆ — exploration in its purest form",
    body:"Knowledge-as-progression games. Outer Wilds is the best exploration game ever made; Blue Prince is 2025's answer; The Witness and Obra Dinn are pure deduction. Low on reflex gameplay, high on curiosity — a great change of pace.",
    picks:["outer-wilds","blue-prince","the-witness","return-of-the-obra-dinn","portal-2"] },
  { icon:"💎", name:"ARPG / Loot", fit:"★★★★☆ — progression and build creativity maxed",
    body:"Path of Exile 2 is the deep end: souls-like bosses plus a 1500-node passive tree. Last Epoch is friendlier. Diablo IV has the best feel. Grim Dawn is offline and forever. All support co-op.",
    picks:["path-of-exile-2","last-epoch","diablo-4","grim-dawn","v-rising"] },
  { icon:"🌲", name:"Survival & Crafting", fit:"★★★★☆ — exploration + creativity + co-op",
    body:"Valheim's biome progression is the genre's best structure. Subnautica is the best solo survival story. Terraria is $10 of infinite content. Project Zomboid is the hardcore end. All great with friends except Subnautica (co-op sequel coming).",
    picks:["valheim","subnautica","terraria","project-zomboid","enshrouded"] },
  { icon:"👊", name:"Character Action & Fighting", fit:"★★★★☆ — skill expression at its purest",
    body:"DMC5's combat is a musical instrument; Hi-Fi Rush is joy; Stellar Blade is the new gold standard for parry action. Fighting games (SF6, Tekken 8, Strive) are the ultimate 1v1 challenge — best with a friend to grow alongside.",
    picks:["devil-may-cry-5","stellar-blade","street-fighter-6","tekken-8","hi-fi-rush"] }
];
